// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.FileUploader = (function() {

    function FileUploader(dropAreaSelector, resultAreaSelector, ajaxUrl) {
      var dropArea, selectArea;
      this.dropAreaSelector = dropAreaSelector;
      this.resultAreaSelector = resultAreaSelector;
      this.ajaxUrl = ajaxUrl;
      this.uploadFile = __bind(this.uploadFile, this);

      this.uploadFiles = __bind(this.uploadFiles, this);

      this.selectFiles = __bind(this.selectFiles, this);

      this.dropFiles = __bind(this.dropFiles, this);

      this.noop = __bind(this.noop, this);

      dropArea = document.querySelectorAll(this.dropAreaSelector)[0];
      dropArea.addEventListener('dragenter', this.noop, false);
      dropArea.addEventListener('dragexit', this.noop, false);
      dropArea.addEventListener('dragover', this.noop, false);
      dropArea.addEventListener('drop', this.dropFiles, false);
      selectArea = document.getElementById('file-input');
      selectArea.addEventListener('change', this.selectFiles, false);
    }

    FileUploader.prototype.noop = function(event) {
      event.stopPropagation();
      return event.preventDefault();
    };

    FileUploader.prototype.dropFiles = function(event) {
      event.stopPropagation();
      event.preventDefault();
      this.noop(event);
      return this.uploadFiles(event.dataTransfer.files);
    };

    FileUploader.prototype.selectFiles = function() {
      var select;
      select = document.getElementById('file-input');
      return this.uploadFiles(select.files);
    };

    FileUploader.prototype.uploadFiles = function(files) {
      var file, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        _results.push(this.uploadFile(file));
      }
      return _results;
    };

    FileUploader.prototype.uploadFile = function(file) {
      var ajaxHash, data,
        _this = this;
      data = new FormData();
      data.append('asset[image]', file);
      ajaxHash = {
        url: this.ajaxUrl,
        type: 'POST',
        data: data,
        cache: false,
        contentType: false,
        processData: false,
        success: function(response) {
          return $(_this.resultAreaSelector).append(response);
        }
      };
      return $.ajax(ajaxHash, 'json');
    };

    return FileUploader;

  })();

}).call(this);
